### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create the HTML, CSS and JavaScript files
- [x] link all the files together in the HTML
- [x] Start the HTML base code for the feature
- [x] ^^ Start with the container, rows and columns
- [x]  Make sure that the page is mobile responsive in HTML 
- [x] Start styling the feature
- [x] Make sure that the page is mobile responsive in CSS using @media
- [x] delete any comments 
- [x] fix styling issue
- [x] make sure code runs with no bugs
- [x] on to the next feature!!
