### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Start on the main.js file for functionality
- [x] Set up DOM elements for the car class
- [x] set up a listener for the dom object 
- [x] set up a function for handling the button's pressed dow (up, down, left, right)
- [x] turn the image element based on the buttons pressed.
- [x] update the position of the car image
- [x] clean up javascript code 
- [x] delete comments
- [x] check for bugs
- [x] On to the next feature!
- [x] https://camo.githubusercontent.com/c3ab3155ae64109a6263bf907dcdc570ef9b9404e88728cea8f65f3faad9469a/68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966
