### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] listen for the spacebar keypress from the user.
- [x] when the spacebar make sure the car moves
- [x] create a data model to hold the car's location
- [x] add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Move your car every 16 milliseconds for a smooth movement.
- [x] reset the location of the car to the top-left location of the car's default location after the car leaves the page.
- [x] Look for bugs
-  [ ] make sure the car moves in a straight line till the end of the page when the user clicks space
-[ ] clean up code
- [x] remove comments 
![image](https://user-images.githubusercontent.com/52221756/126703705-c739810a-994c-40f8-8a7a-4334841499f7.png)
